### ISSUE TITLE
Split the .github/workflows/build.yaml into two

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop-rdx-ai-workbench#10]
Split the .github/workflows/build.yaml into two workflows 

- the build workflow that's triggered on PRs, which only builds the extension
- the publish workflow that's triggered on push to `main`, when a release tag is created which builds and publishes the extension to GitHub packages

**Comment by jandubois** [comment]
I think #23 implements this. It only pushes the image when we push a tag, but I think that is all we need, we need to publish an image on pushes to `main`.
