### ISSUE TITLE
Disable ENABLE_EVALUATION_ARENA_MODELS by default

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/rancher-desktop-rdx-ai-workbench#12]
open webui upstream recently added a models evaluation feature, which can be accessible at `Admin Panel > Evaluations`. 
An option associated with the Evaluation feature is the ARENA Models when enabled will add a model option called `Arena Model` to the models selector drop down. If `Arena Model` is selected as the active model then the chat will randomly direct the questions to one of the Arena models. When users click 👍or 👎on a response, the feedback is stored in the back end and eventually the models performance/feedback is presented in the `Admin Panel > Evaluations` dashboard. This feature makes more sense when open webui is deployed in prod for a larger group and when an admin wants to know which models are more useful for the group etc.. For a single user usage the feature might not be of much value in most cases so better to disable the feature so the confusing `Arena Model`  option doesn't show up in the models selector drop down. If users want this feature they can always enable it at `Admin Panel > Settings > Evaluations`.

**Comment by jandubois** [comment]
> If users want this feature they can always enable it at `Admin Panel > Settings > Evaluations`.

So this just means starting with different default settings, right? Where are the settings stored, inside the extension directory, or globally in a user config directory?

**Comment by gunamata** [comment]
Yes, it just means starting with different default settings. The settings are stored in a user config directory in a docker volume.

**Comment by gunamata** [comment]
Addressed by #14
