### ISSUE TITLE
Write a PIDFILE when we start ollama from the extension

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop-rdx-ai-workbench#2]
Right now we only stop the ollama process when the binary is stored inside the extension directory.

But that does not cover the case when ollama is installed in the default system location, but not currently running when the extension is started:

The extension will start ollama, but not stop it again when the user terminates Rancher Desktop.

Checking the PID against the PIDFILE instead of checking the binary location would allow us to do the right thing in all scenarios.

This issue has been extracted from https://github.com/rancher-sandbox/rancher-desktop-rdx-open-webui/pull/14#issuecomment-2403672848 so rancher-sandbox/rancher-desktop-rdx-open-webui2#14 can be merged as-is.

**Comment by mook-as** [comment]
Instead of using a pidfile, we're just using process groups (on linux/darwin) or jobs (windows).  This will be done from the RD side so that we don't have to worry about other extensions having the same issue.
